apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-store
  name: thanos-store
spec:
  ports:
  - name: 10901-tcp
    port: 10901
    protocol: TCP
    targetPort: 10901
  - name: 10902-tcp
    port: 10902
    protocol: TCP
    targetPort: 10902
  selector:
    app: thanos-store
  sessionAffinity: None
  type: ClusterIP
