apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-querier
  name: thanos-querier
spec:
  ports:
  - name: 9090-tcp
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: 10901-tcp
    port: 10901
    protocol: TCP
    targetPort: 10901
  selector:
    app: thanos-querier
  sessionAffinity: None
  type: ClusterIP
